# Jekyll Resume Theme

# Site settings
title: Jekyll Resume
email: hello@mattcouchman.co.uk
description: Jekyll Resume is a mega simple resume theme for Jekyll.
baseurl: ""
url: "http://mattcouchman.co.uk/jekyll-resume"
twitter_username: mattcouchman
github_username:  mattcouchman

# Build settings
markdown: kramdown
